"use server"

import { Resend } from "resend"

const resend = new Resend(process.env.RESEND_API_KEY)

// Interface for email options
interface EmailOptions {
  to: string
  subject: string
  summaryText: string
  meetingTitle: string
  meetingDate: string
}

// Send email using Resend API
export async function sendMeetingSummaryEmail({ to, subject, summaryText, meetingTitle, meetingDate }: EmailOptions) {
  try {
    const emailContent = `
${meetingTitle} - Meeting Summary
Date: ${meetingDate}

${summaryText}

---
Generated by L10 Meeting Agenda Timer
    `.trim()

    const { data, error } = await resend.emails.send({
      from: "L10 Meeting Timer <noreply@turnanewleaf.org>",
      to: [to],
      subject: subject,
      text: emailContent,
    })

    if (error) {
      console.error("Resend API error:", error)
      return {
        success: false,
        error: error.message || "Failed to send email",
        technicalDetails: JSON.stringify(error),
      }
    }

    console.log("Email sent successfully:", data)

    return {
      success: true,
      message: "Email sent successfully",
      data,
    }
  } catch (error: any) {
    console.error("Error sending email:", error)

    return {
      success: false,
      error: error?.message || "Unknown error occurred",
      technicalDetails: JSON.stringify(error),
    }
  }
}
